from app.api.routes.auth import router as auth_router
from app.api.routes.users import router as users_router
from app.api.routes.customers import router as customers_router
from app.api.routes.devices import router as devices_router
from app.api.routes.solutions import router as solutions_router
from app.api.routes.device_solutions import router as device_solutions_router
from app.api.routes.customer_solutions import router as customer_solutions_router
from app.api.routes.device_metrics import router as device_metrics_router
from app.api.routes.services.city_eye.city_eye_analytics import router as city_eye_analytics_router
from app.api.routes.device_commands import router as device_commands_router
from app.api.routes.sse import router as sse_router
