from app.crud.base import CRUDBase
from app.crud.user import user
from app.crud.customer import customer
from app.crud.device import device
from app.crud.solution import solution
from app.crud.customer_solution import customer_solution
from app.crud.device_solution import device_solution
from app.crud.crud_city_eye_analytics import crud_city_eye_analytics
from app.crud.device_command import device_command
from app.crud.audit_log import audit_log
from app.crud.password_reset_token import password_reset_token
from app.crud.job import job
from app.crud.crud_ai_model import ai_model
