"""Add PACKAGE_DEPLOYMENT for enum JobType

Revision ID: 04f87c5a6322
Revises: ba95fef68bd4
Create Date: 2025-08-14 00:14:50.032504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f87c5a6322'
down_revision = 'ba95fef68bd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE JobType ADD VALUE IF NOT EXISTS 'PACKAGE_DEPLOYMENT'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###