"""update device command CommandStatus Type

Revision ID: 231619edbc1f
Revises: dfb514edcf75
Create Date: 2025-07-01 11:57:27.908574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231619edbc1f'
down_revision = 'dfb514edcf75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE CommandStatus ADD VALUE IF NOT EXISTS 'ALREADY_STREAMING'")
    op.execute("ALTER TYPE CommandStatus ADD VALUE IF NOT EXISTS 'NOT_STREAMING'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###