"""remove inactive enum type from device status

Revision ID: 35e7793903cd
Revises: 5c2065c5853d
Create Date: 2025-05-13 13:25:22.948405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '35e7793903cd'
down_revision = '5c2065c5853d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create a new enum type without INACTIVE
    op.execute("""
        CREATE TYPE device_status_new AS ENUM (
            'CREATED', 'PROVISIONED', 'ACTIVE', 'MAINTENANCE', 'DECOMMISSIONED'
        )               
    """)

    # Update existing records with INACTIVE status to DECOMMISSIONED
    op.execute("""
        UPDATE devices 
        SET status = 'DECOMMISSIONED' 
        WHERE status = 'INACTIVE'
    """)
    
    # Alter the column to use the new enum type
    # First, drop the default
    op.execute("ALTER TABLE devices ALTER COLUMN status DROP DEFAULT")


    # Then alter the column type
    op.execute("""
        ALTER TABLE devices
        ALTER COLUMN status TYPE device_status_new
        USING status::text::device_status_new
    """)

    # Add back the default if necessary
    op.execute("ALTER TABLE devices ALTER COLUMN status SET DEFAULT 'CREATED'")

    
    # Drop the old enum type
    op.execute("DROP TYPE device_status")

    # Rename the new enum type to the original name
    op.execute("ALTER TYPE device_status_new RENAME TO device_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the old enum type with INACTIVE
    op.execute("""
        CREATE TYPE device_status_old AS ENUM (
            'CREATED', 'PROVISIONED', 'ACTIVE', 'INACTIVE', 'MAINTENANCE', 'DECOMMISSIONED'
        )
    """)
    
    # Alter the column to use the old enum type
    # First, drop the default
    op.execute("ALTER TABLE devices ALTER COLUMN status DROP DEFAULT")
    
    # Then alter the column type
    op.execute("""
        ALTER TABLE devices
        ALTER COLUMN status TYPE device_status_old
        USING status::text::device_status_old
    """)
    
    # Add back the default
    op.execute("ALTER TABLE devices ALTER COLUMN status SET DEFAULT 'CREATED'")
    
    # Drop the new enum type
    op.execute("DROP TYPE device_status")
    
    # Rename the old enum type back to the original name
    op.execute("ALTER TYPE device_status_old RENAME TO device_status")
    # ### end Alembic commands ###