"""Create Solution, Customer_Solution, Device_Soulution Tables

Revision ID: 5008ccac06ed
Revises: b3d8bb214dbc
Create Date: 2025-05-02 10:36:30.872383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5008ccac06ed'
down_revision = 'b3d8bb214dbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solutions',
    sa.Column('solution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('compatibility', sa.JSON(), nullable=False),
    sa.Column('configuration_template', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'BETA', 'DEPRECATED', name='solutionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('solution_id')
    )
    op.create_table('customer_solutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=False),
    sa.Column('license_status', sa.Enum('ACTIVE', 'SUSPENDED', 'EXPIRED', name='licensestatus'), nullable=False),
    sa.Column('max_devices', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('configuration_template', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.solution_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_solutions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PROVISIONING', 'ACTIVE', 'ERROR', 'STOPPED', name='devicesolutionstatus'), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('version_deployed', sa.String(), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.solution_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_solutions')
    op.drop_table('customer_solutions')
    op.drop_table('solutions')

    # Drop the enum types
    op.execute('DROP TYPE IF EXISTS devicesolutionstatus')
    op.execute('DROP TYPE IF EXISTS licensestatus')
    op.execute('DROP TYPE IF EXISTS solutionstatus')
    # ### end Alembic commands ###