"""Add provision based city eye analytics tables

Revision ID: 8fd43cf310d1
Revises: d20c9cd626c0
Create Date: 2025-09-26 13:10:28.721952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd43cf310d1'
down_revision = 'd20c9cd626c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_eye_provisioned_human_data',
    sa.Column('data_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=False),
    sa.Column('device_solution_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('polygon_id_in', sa.String(), nullable=False),
    sa.Column('polygon_id_out', sa.String(), nullable=False),
    sa.Column('male_less_than_18', sa.Integer(), nullable=False),
    sa.Column('female_less_than_18', sa.Integer(), nullable=False),
    sa.Column('male_18_to_29', sa.Integer(), nullable=False),
    sa.Column('female_18_to_29', sa.Integer(), nullable=False),
    sa.Column('male_30_to_49', sa.Integer(), nullable=False),
    sa.Column('female_30_to_49', sa.Integer(), nullable=False),
    sa.Column('male_50_to_64', sa.Integer(), nullable=False),
    sa.Column('female_50_to_64', sa.Integer(), nullable=False),
    sa.Column('male_65_plus', sa.Integer(), nullable=False),
    sa.Column('female_65_plus', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['device_solution_id'], ['device_solutions.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.solution_id'], ),
    sa.PrimaryKeyConstraint('data_id')
    )
    op.create_table('city_eye_provisioned_traffic_data',
    sa.Column('data_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=False),
    sa.Column('device_solution_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('polygon_id_in', sa.String(), nullable=False),
    sa.Column('polygon_id_out', sa.String(), nullable=False),
    sa.Column('large', sa.Integer(), nullable=False),
    sa.Column('normal', sa.Integer(), nullable=False),
    sa.Column('bicycle', sa.Integer(), nullable=False),
    sa.Column('motorcycle', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['device_solution_id'], ['device_solutions.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.solution_id'], ),
    sa.PrimaryKeyConstraint('data_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city_eye_provisioned_traffic_data')
    op.drop_table('city_eye_provisioned_human_data')
    # ### end Alembic commands ###