"""Add archived to job status

Revision ID: 9adeebc618d7
Revises: c3d8aa88baea
Create Date: 2025-08-03 16:40:11.963556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9adeebc618d7'
down_revision = 'c3d8aa88baea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE JobStatus ADD VALUE IF NOT EXISTS 'ARCHIVED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###