"""make status columns nullable in solutions table

Revision ID: a3863e02fec2
Revises: b0b6a71b2fa5
Create Date: 2025-09-17 16:26:34.255561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3863e02fec2'
down_revision = 'b0b6a71b2fa5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solutions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'BETA', 'DEPRECATED', name='solutionstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solutions', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'BETA', 'DEPRECATED', name='solutionstatus'),
               nullable=False)
    # ### end Alembic commands ###