"""make table columns nullable in customer_solution and solution_device table

Revision ID: b0b6a71b2fa5
Revises: 5f08a94e540c
Create Date: 2025-09-17 16:21:22.850754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0b6a71b2fa5'
down_revision = '5f08a94e540c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_solutions', 'max_devices',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('device_solutions', 'status',
               existing_type=postgresql.ENUM('PROVISIONING', 'ACTIVE', 'ERROR', 'STOPPED', name='devicesolutionstatus'),
               nullable=True)
    op.alter_column('device_solutions', 'version_deployed',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_solutions', 'version_deployed',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('device_solutions', 'status',
               existing_type=postgresql.ENUM('PROVISIONING', 'ACTIVE', 'ERROR', 'STOPPED', name='devicesolutionstatus'),
               nullable=False)
    op.alter_column('customer_solutions', 'max_devices',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###