"""create device table

Revision ID: b3d8bb214dbc
Revises: 33b21c44cbab
Create Date: 2025-04-29 16:18:30.616897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3d8bb214dbc'
down_revision = '33b21c44cbab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('thing_name', sa.String(), nullable=True),
    sa.Column('thing_arn', sa.String(), nullable=True),
    sa.Column('certificate_id', sa.String(), nullable=True),
    sa.Column('certificate_arn', sa.String(), nullable=True),
    sa.Column('certificate_path', sa.String(), nullable=True),
    sa.Column('private_key_path', sa.String(), nullable=True),
    sa.Column('device_type', sa.Enum('NVIDIA_JETSON', 'RASPBERRY_PI', name='device_type'), nullable=False),
    sa.Column('firmware_version', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PROVISIONED', 'ACTIVE', 'INACTIVE', 'MAINTENANCE', 'DECOMMISSIONED', name='device_status'), nullable=False),
    sa.Column('last_connected', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('thing_name')
    )
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###