"""remove column from solution_package_model

Revision ID: ba95fef68bd4
Revises: 422ad7a0e122
Create Date: 2025-08-10 23:40:36.559688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba95fef68bd4'
down_revision = '422ad7a0e122'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solution_package_models', 'model_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solution_package_models', sa.Column('model_role', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###