"""Create device_commands table

Revision ID: c1116619f5d3
Revises: 35e7793903cd
Create Date: 2025-06-08 15:37:26.604569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1116619f5d3'
down_revision = '35e7793903cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_commands',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('solution_id', sa.UUID(), nullable=False),
    sa.Column('command_type', sa.Enum('CAPTURE_IMAGE', 'UPDATE_CONFIG', 'RESTART_SERVICE', 'UPDATE_POLYGON', 'GET_STATUS', name='commandtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'TIMEOUT', name='commandstatus'), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.solution_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_commands')
    # ### end Alembic commands ###