"""add latest job id column in device table

Revision ID: c3d8aa88baea
Revises: c322602bbfd8
Create Date: 2025-08-03 15:36:23.207998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d8aa88baea'
down_revision = 'c322602bbfd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('latest_job_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'devices', 'jobs', ['latest_job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'latest_job_id')
    # ### end Alembic commands ###