"""remove status column from solution, device solution, max_devices f
rom customer_solution and remove DeviceSolutionStatus enum type

Revision ID: d20c9cd626c0
Revises: a3863e02fec2
Create Date: 2025-09-17 18:58:49.144163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd20c9cd626c0'
down_revision = 'a3863e02fec2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_solutions', 'max_devices')
    op.drop_column('device_solutions', 'status')
    op.drop_column('device_solutions', 'version_deployed')
    op.drop_column('solutions', 'version')
    
    # Manually drop the DeviceSolutionStatus enum type
    op.execute("DROP TYPE IF EXISTS devicesolutionstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually recreate the DeviceSolutionStatus enum type
    op.execute("CREATE TYPE devicesolutionstatus AS ENUM ('PROVISIONING', 'ACTIVE', 'ERROR', 'STOPPED')")
    
    op.add_column('solutions', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('device_solutions', sa.Column('version_deployed', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('device_solutions', sa.Column('status', postgresql.ENUM('PROVISIONING', 'ACTIVE', 'ERROR', 'STOPPED', name='devicesolutionstatus'), autoincrement=False, nullable=True))
    op.add_column('customer_solutions', sa.Column('max_devices', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###