"""add indices to city eye human and traffic tables

Revision ID: d9c1eff0850e
Revises: 04f87c5a6322
Create Date: 2025-09-08 00:19:39.412860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c1eff0850e'
down_revision = '04f87c5a6322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solutions', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('idx_human_timestamp_device', 'city_eye_human_data', ['timestamp', 'device_id'], unique=False)
    op.create_index('idx_human_polygon_in_out', 'city_eye_human_data', ['polygon_id_in', 'polygon_id_out'], unique=False)
    op.create_index('idx_traffic_timestamp_device', 'city_eye_traffic_data', ['timestamp', 'device_id'], unique=False)
    op.create_index('idx_traffic_polygon_in_out', 'city_eye_traffic_data', ['polygon_id_in', 'polygon_id_out'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solutions', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('idx_traffic_polygon_in_out', table_name='city_eye_traffic_data')
    op.drop_index('idx_traffic_timestamp_device', table_name='city_eye_traffic_data')
    op.drop_index('idx_human_polygon_in_out', table_name='city_eye_human_data')
    op.drop_index('idx_human_timestamp_device', table_name='city_eye_human_data')
    # ### end Alembic commands ###