"""add new command type for table DeviceCommand

Revision ID: dfb514edcf75
Revises: f74f5cb854c6
Create Date: 2025-06-23 19:38:46.809541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfb514edcf75'
down_revision = 'f74f5cb854c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE commandtype ADD VALUE IF NOT EXISTS 'START_LIVE_STREAM'")
    op.execute("ALTER TYPE commandtype ADD VALUE IF NOT EXISTS 'STOP_LIVE_STREAM'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###