"""add longitude and lattitude column in device

Revision ID: f74f5cb854c6
Revises: c1116619f5d3
Create Date: 2025-06-12 09:58:33.073085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74f5cb854c6'
down_revision = 'c1116619f5d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('devices', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'longitude')
    op.drop_column('devices', 'latitude')
    # ### end Alembic commands ###