platform: 
    type: HAILO8
    display: false
    network: yolov8m
    postprocess_dir: /usr/lib/aarch64-linux-gnu/hailo/tappas/post_processes/
    # source_type: file
    source_type: ipcamera
    detection_model_path: /opt/models/detection/yolov8m.hef
    attribute_model_path: /opt/models/classification/person_attr_resnet_v1_18_2.hef
    postprocess_so_path: /usr/lib/aarch64-linux-gnu/hailo/tappas/post_processes/libyolo_hailortpp_postprocess.so
    postprocess_function_name: filter_letterbox
    labels_json: ""
    disable_sync: false
    disable_callback: false
    debug_pipeline: true
    measure_fps: true
    sink_type: fake # fake or dispplay or file


solution:
    name: city-eye
    batch_size: 16
    use_frame: True
    nms_score_threshold: 0.3
    nms_iou_threshold: 0.45
    xlines_cfg_path: /opt/configs/xlines_cfg.json
    count_output_path: /opt/configs/resources/data/count_result.json
    sqlite_base_dir: /opt/db
    sync_batch_size: 100
    sync_interval_seconds: 600
    db_credential_secret_name: cc-platform_database_credentials
    test: true

    input: 
        video_width: 1280
        video_height: 720
        video_format: "RGB"
        type: rpi
        file_path: rpi
        # type: file
        # file_path: resources/data/cam9001_20241029_09.mp4
        # IP Camera configuration
        # type: ipcamera
        # camera_url: "rtsp://192.168.111.155/axis-media/media.amp"  # Base URL of Axis camera
        # username: "root"
        # password: "12San456"  
        # # Axis camera specific settings
        # use_rtsp: true  # Use RTSP stream (recommended) or HTTP MJPEG
        # rtsp_port: 554  # Default RTSP port
        # fps: 45
        # compression: 45  # H.264 compression level (0-100, lower = better quality)
        # stream_profile: "quality"  # Axis stream profile name


    output:
        type: cityeye
        streaming: true
        streaming_fps: 5
        streaming_host: "0.0.0.0"
        streaming_port: 7000
        

    # Cloud configuration
    cloud:
        provider: aws_iot
        region: ap-northeast-1
        endpoint: "a23bd20ty64577-ats.iot.ap-northeast-1.amazonaws.com"
        certs_dir: "/opt/certificates"
        solution_type: "cityeye"
        enable_compression: true
        config_shadow_name: "XLinesConfigShadow"
        s3_bucket_name: cc-captured-images
        capture_image_command_suffix: capture_image 
        stream_command_suffix: stream/+
