platform: 
    type: HAILO8
    display: false
    network: yolov8m
    postprocess_dir: /usr/lib/aarch64-linux-gnu/hailo/tappas/post_processes/
    source_type: file
    detection_model_path: /opt/models/detection/yolov8m.hef
    attribute_model_path: /opt/models/classification/person_attr_resnet_v1_18.hef
    postprocess_so_path: /home/Raspi5_2/hailo-rpi5-examples/venv_hailo_rpi5_examples/lib/python3.11/site-packages/resources/libyolo_hailortpp_postprocess.so
    postprocess_function_name: filter_letterbox
    labels_json: ""
    disable_sync: false
    disable_callback: false
    debug_pipeline: true
    measure_fps: true
    sink_type: fake # fake or dispplay or file


solution:
    name: flow-eye
    batch_size: 16
    use_frame: True
    nms_score_threshold: 0.3
    nms_iou_threshold: 0.45
    xlines_cfg_path: /home/Raspi5_2/ws/nixon/cc-edge-analytics/configs/xlines_cfg.json
    count_output_path: /home/Raspi5_2/ws/nixon/cc-edge-analytics/resources/data/count_result.json

    tracking:
        track_fps: 30
        track_thresh: 0.4
        track_buffer: 30
        match_thresh: 0.75
        min_box_area: 300

    input: 
        video_width: 1280
        video_height: 720
        video_format: "RGB"
        # type: rpi
        # file_path: rpi
        type: file
        file_path: resources/data/ch01_00000000143000000.mp4
    output:
        type: default
        streaming: true
        streaming_fps: 0.5
        streaming_host: "0.0.0.0"
        streaming_port: 7000
        

    # # Cloud configuration
    # cloud:
    #     provider: aws_iot
    #     aws_iot_endpoint: "your-endpoint.iot.region.amazonaws.com"
    #     cert_path: "/path/to/certificate.pem"
    #     private_key_path: "/path/to/private.key"
    #     root_ca_path: "/path/to/root-ca.pem"
    #     device_id: "unique-device-id"
    #     solution_type: "flow_eye"
    #     report_interval: 60 